# ****************************************************************************
# NOTES:
#
# This is an example of a production deployment that uses GitHub Pages along
# with a second "production" GitHub organisation. If you prefer to implement
# your own workflow, or do not need production deployments, then you should
# delete this file.
#
# In order for this to work, you must replace PRODUCTION_ORGANISATION below
# with the name of your production GitHub organisation, under REPOSITORY_NAME.
# You must also replace PRODUCTION_REPOSITORY below with the name of your
# production data repository.
#
# For example, if your production organisation is "my-stats-org", and your
# production data repository is "sdg-data", then use:
#
# REPOSITORY_NAME: my-stats-org/sdg-data
#
# In addition, to set up automated production releases, you would need to
# replace STAGING_ORGANISATION and STAGING_SITE_REPOSITORY below.
#
# ****************************************************************************

name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Build data
      run: |
        python scripts/build_data.py
    - name: Place public files
      run: |
        cp public/robots-prod.txt _site/robots.txt
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        REPOSITORY_NAME: PRODUCTION_ORGANISATION/PRODUCTION_REPOSITORY
        ACCESS_TOKEN: ${{ secrets.token }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
    - name: Waiting 4 minutes for production data deployment
      run: |
        sleep 240
    - name: Rebuild site
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.token }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/STAGING_ORGANISATION/STAGING_SITE_REPOSITORY/actions/workflows/deploy-to-production.yml/dispatches \
          -d '{"ref":"master"}'
